spring.application.name=cems-backend
spring.data.mongodb.uri=mongodb+srv://pushkarsharma100107_db_user:VtE9elbOU5x8ka4k@cluster0.v9ftjb7.mongodb.net/cems-db?retryWrites=true&w=majority&appName=Cluster0
server.port=8080
